Repository gus5900000/AugustinVerissimo, pull requests merged in 2025-04, with the labels that each got.

#12 feat/add better hover
  index.html
  script/index.js
  style/index.css
Labels: Review effort 2/5

#13 refactor/change markdown format
  project/ainao.md
  project/cinescope.md
  project/luvio.md
  project/my_cinema.md
  project/netninja.md
  project/snake_IA.md
  project/space-invader.md
  project/toolbox.md
  script/project.js
Labels: Review effort 2/5

#14 feat/add epigusto project
  project/epigusto.md
  script/project.js
Labels: Review effort 1/5

#15 feat/add guscss project
  project/GusCSS.md
  script/project.js
Labels: Review effort 1/5

#16 feat/add tweet academie
  project/tweet_academie.md
  script/project.js
Labels: Review effort 1/5

#17 Preprod
  LICENSE
  index.html
  project/GusCSS.md
  project/ainao.md
  project/cinescope.md
  project/epigusto.md
  project/luvio.md
  project/my_cinema.md
  project/netninja.md
  project/snake_IA.md
  project/space-invader.md
  project/toolbox.md
  project/tweet_academie.md
  script/index.js
  script/project.js
  style/index.css
Labels: Review effort 3/5
